### ISSUE TITLE
General questions about the command line tool (and the API design)

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadActor#28]
Feedback at this moment: 
it might be useful if we can discuss the requirements towards users, or say, different kinds of possibilities that might happen. 

Is it a good strategy to doubt every cell could be a typo? This will require a lot of all kind checking and the tool needs a priority system. What if the user made mistakes with person_id, family_name, and wikidata_id? As a human we know the chance is rare, but to think in computing way, the logic requires taking care of all possible conditions.
To avoid the possibility of major rewrites, a discussion about this will be helpful. @duncdrum 
For example, if the input `person_id` exists in ReadAct, can the tool overwrite the whole line with the information from ReadAct? Or the tool must compare the rest column values with the ReadAct ones, and use a weighting system again, to decide, among person name, wikipedia link, wikidata id, which one is the source of the authenticity verification that we with use to compare with the whole row? Since the tool is required to check if the row must be changed or not and to mark in the `last_modified` and `last_modified_by` fields.

And how to deal with the two new columns `wikipedia_link` and `wikidata_id` with the `Person.csv` in ReadAct?

**Comment by duncdrum** [comment]
IDs (primary keys) are special, we should start from the assumption that these are correct. If a new table should reassign a person_id that is already used by Readact there should be a warning in the `Person.note` cell. 

Practically speaking the tool needs to check if the pair of `person_id` and  `wikidata_id` differ between a user's file and that  of ReadAct. So if either ID is already present in ReadAct but not as part of the same pair, then there is a data error. The Tool should inform the user by appending the note field (and print a meaningful message to the CLI). 

As a rule of thumb the tool should never rewrite person_ids, our validation tool already makes sure that these are unique. Changing the IDs of primary entities usually also requires updating foreign keys in a number of other tables, which is then a task required of the user. 

Once we have the Wikidata_id added to the table schema, these will have to be validated as unique as well. 
If person_id and wikidata_id are both matching a single row in ReadAct all remaining entries are open to be overwritten, and we assume human error as the most likely source of conflicts.

**Comment by whalekeykeeper** [comment]
> IDs (primary keys) are special, we should start from the assumption that these are correct. If a new table should reassign a person_id that is already used by Readact there should be a warning in the `Person.note` cell.
> 
> Practically speaking the tool needs to check if the pair of `person_id` and `wikidata_id` differ between a user's file and that of ReadAct. So if either ID is already present in ReadAct but not as part of the same pair, then there is a data error. The Tool should inform the user by appending the note field (and print a meaningful message to the CLI).
> 
> As a rule of thumb the tool should never rewrite person_ids, our validation tool already makes sure that these are unique. Changing the IDs of primary entities usually also requires updating foreign keys in a number of other tables, which is then a task required of the user.
> 
> Once we have the Wikidata_id added to the table schema, these will have to be validated as unique as well. If `person_id` and `wikidata_id` are both matching a single row in ReadAct all remaining entries are open to be overwritten, and we assume human error as the most likely source of conflicts.

It is implemented in a way that `person_id` and `wikidata_id`(if there's one) are the key for comparing with the database on GitHub. If any match, the different part will be overwritten. If there's no match, then `family_name`, `first_name` and `name_lang` will be used to query if there is such a person entity, if yes, fill the table with a new `person_id`, if no, a warning message will be added into `note`.

Questions:
1. How about `wikipedia_lin` field?
2. It seems that we should update the `Person.csv` in ReadAct to include column `wikidata_id` and `wikipedia_link`(instead of `source_1`) if we want to use `wikidata_id`.
