### ISSUE TITLE
CLI wrapper

### ISSUE THREAD

**Issue by duncdrum** [readchina/ReadActor#37]
here is some usable hints for making the tool more userfriendly 

https://pybit.es/articles/how-to-package-and-deploy-cli-apps/

**Comment by duncdrum** [comment]
some more packages that might be of interest: 
- https://github.com/datafolklabs/cement 
- https://docs.openstack.org/cliff/latest/install/index.html

**Comment by whalekeykeeper** [comment]
I found [click](https://click.palletsprojects.com/en/8.1.x/) supports [setuptools](https://click.palletsprojects.com/en/8.1.x/setuptools/?highlight=setuptools) which is similar to the wrapper function
