### ISSUE TITLE
QIDs for all or part of the entries in Space.csv?

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadActor#51]
@duncdrum The script will first compare the geo coordinates with `OpenStreetMap`, and then try to get the `QIDs` and compare the coordinates with `Wikidata` information.

Is it necessary to try to get all the QIDs for the `Space.csv` table?

**Comment by duncdrum** [comment]
While I wouldn't go as far to say its strictly necessary, it would certainly enhance our data set and increase consistency to get QIDs for `Space.csv`.
