### ISSUE TITLE
Warning or error: user input geo location conflicts with the geo location found by querying Wikidata with space_name

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadActor#67]
See the cell 23 in the[ Space mindmap](https://github.com/readchina/ReadActor/blob/use-click/src/utility/Mindmap_space.png).

Assume user didn't input a `wikidata_id` for one row, but did input geo location (`lat` &`long`) and this geo location failed the query with OSM.
ReadActor queried Wikidata with the `space_name` and found a match.
Assume this match has a geo location property (P625), which is to say, `lat` & `long`.
Should it be a warning or an error if these two geo location are different?

If it is warning, the tool won't terminate and the user can do a manual check after running the tool for the entire file if they care about the warning.
If it is error, the tool will be terminate, the user has to check immediately and put `skip` in `note`.

see #63

**Comment by duncdrum** [comment]
I expect this to be quite common, as deciding the long lat of places leaves a lot of wiggle room. I d say `warning`
