### ISSUE TITLE
space in Person.csv not in Space.csv

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadActor#72]
What if we have a space(place/location) entity in `Person.csv` because of either user input or Wikidata query, and this space entity is not in the `Space.csv`?

The current strategy is to raise an `error`, so that the user must update Space.csv first. However, there is a risk that the user cannot see the potential error if the space entity will only be gained after the Wikidata query.

Should the tool ReadActor include a new section of code to update `Space.csv` basing on `Person.csv`?  But it is certainly increasing the complexity of this tool. Is it necessary to do this now?

**Comment by duncdrum** [comment]
Ok this seems to be two separate problems.

1. If user adds a `space_id` in `person.csv` (or any other table) that has no corresponding value on `space.csv` that will create a validation error. As dereferenced keys are caught and flagged by validation. ReadActor doesn't need to check for those or do anything about them. 
2. If the tool adds finds e.g. a birthplace on wikidata, but the location has no existing space_id, it will need to create one and add it to the `space.csv` table
