### ISSUE TITLE
warning about duplicate space_name

### ISSUE THREAD

**Issue by duncdrum** [readchina/ReadActor#80]
https://github.com/readchina/ReadAct/actions/runs/3094012559/jobs/5185508475#step:10:7083

I m not quite sure what to make of this, it could point to a bug, or might be harmless and just an unnecessary warning.

**Comment by whalekeykeeper** [comment]
The following spaces have duplicated space_name in the Space.csv in 2.0-RC-patch branch:

Leipzig

Hubei

Heilongjiang

Haining

**Comment by duncdrum** [comment]
Interesting so we need to make our validation more strict and fix the duplicate entries.
